### ISSUE TITLE
richardson_lucy: value error unsupported keyword arguments for mode 'reflect': {'constant_values'}

### ISSUE THREAD

**Issue by thawn** [BiAPoL/PoL-BioImage-Analysis-TS-GPU-Accelerated-Image-Analysis#10]
In notebook 6_decon_bead_edge_handling.ipynb
cell 5, I get a `ValueError: unsupported keyword arguments for mode 'reflect': {'constant_values'}`
<details><pre>regularization_factor=0

im_decon_clij_nc = richardson_lucy_nc(bead, psf, iterations , regularization_factor)

im_decon_clij= richardson_lucy(bead, psf, iterations , regularization_factor)
</pre>

<pre>
​get lib

Richardson Lucy Started
0 10 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350 360 370 380 390 400 410 420 430 440 450 460 470 480 490 500 510 520 530 540 550 560 570 580 590 600 610 620 630 640 650 660 670 680 690 700 710 720 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890 900 910 920 930 940 950 960 970 980 990 
Richardson Lucy Finished

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 3
      1 regularization_factor=0
      2 im_decon_clij_nc = richardson_lucy_nc(bead, psf, iterations , regularization_factor)
----> 3 im_decon_clij= richardson_lucy(bead, psf, iterations , regularization_factor)

File /app/env/lib/python3.9/site-packages/clij2fft/richardson_lucy.py:33, in richardson_lucy(img, psf, numiterations, regularizationfactor, first_guess, lib)
     30 extended_size = get_next_smooth(padded_size)
     32 # pad image and psf to next smooth size
---> 33 img, _ = pad(img, extended_size,'reflect')
     34 psf, _ = pad(psf, extended_size, 'constant')    
     36 # shift psf so center is at 0,0

File /app/env/lib/python3.9/site-packages/clij2fft/pad.py:90, in pad(img, paddedsize, mode, constant_values)
     79 """ pad image to paddedsize
     80 
     81 Args:
   (...)
     87     [nd array]: padded image
     88 """
     89 padding = tuple(map(lambda i,j: ( math.ceil((i-j)/2), math.floor((i-j)/2) ),paddedsize,img.shape))
---> 90 return np.pad(img, padding,mode, constant_values=constant_values), padding

File <__array_function__ internals>:180, in pad(*args, **kwargs)

File /app/env/lib/python3.9/site-packages/numpy/lib/arraypad.py:785, in pad(array, pad_width, mode, **kwargs)
    783     raise ValueError("mode '{}' is not supported".format(mode)) from None
    784 if unsupported_kwargs:
--> 785     raise ValueError("unsupported keyword arguments for mode '{}': {}"
    786                      .format(mode, unsupported_kwargs))
    788 stat_functions = {"maximum": np.amax, "minimum": np.amin,
    789                   "mean": np.mean, "median": np.median}
    791 # Create array with final shape and original values
    792 # (padded area is undefined)

ValueError: unsupported keyword arguments for mode 'reflect': {'constant_values'}</pre></details>

**Comment by bnorthan** [comment]
Hopefully this is fixed now with [this change](https://github.com/clij/clij2-fft/commit/25a2ae22b5197dd1f76f037d7fe0bf521484b35a)

Get latest of clij2-fft to test.   It should be at version 0.18 now.

**Comment by thawn** [comment]
I can confirm that this is fixed in clij2-fft v0.18 - thanks a lot for the quick fix :-)
