### ISSUE TITLE
TOC doesn't list all pages

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/PoL-BioImage-Analysis-TS-GPU-Accelerated-Image-Analysis#31]
The sub-pages of the pytroch session are not show in the TOC:

![image](https://github.com/BiAPoL/PoL-BioImage-Analysis-TS-GPU-Accelerated-Image-Analysis/assets/12660498/8552a6bc-abcc-4563-a6c4-570ce0b89dab)

I've tried some things and couldn't figure it out...

**Comment by jo-mueller** [comment]
@haesleinhuepf The `readme.md` of that section had two top-level (`#`) headlines, which caused Jupyter book to fail building correctly. Fixed it :)
