### ISSUE TITLE
Jupyter Widgets don't work on Taurus' Jupyter hub

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/PoL-BioImage-Analysis-TS-GPU-Accelerated-Image-Analysis#5]
[stackview](https://github.com/haesleinhuepf/stackview) cannot be used at the moment on taurus' jupyter hub. It doesn't show Jupyter widgets but this error instead:

![image](https://github.com/BiAPoL/PoL-BioImage-Analysis-TS-GPU-Accelerated-Image-Analysis/assets/12660498/1228d863-b70c-4f1c-913b-6f24963c4a5e)

See [this notebook](https://github.com/BiAPoL/PoL-BioImage-Analysis-TS-GPU-Accelerated-Image-Analysis/blob/beb94d19bb2801138e1394dd73adf5103e3b195c/docs/50_Clesperanto_on_HPC/stackview.ipynb).

Related PR:
* https://github.com/BiAPoL/PoL-BioImage-Analysis-TS-GPU-Accelerated-Image-Analysis/pull/4

**Comment by haesleinhuepf** [comment]
_Maybe_ because the Jupyter hub is outdated on the cluster:

![image](https://github.com/BiAPoL/PoL-BioImage-Analysis-TS-GPU-Accelerated-Image-Analysis/assets/12660498/f5ba3334-4714-4d2e-befa-66f8d4d6801f)

Locally, stackview works and Juypter hub has this version:

![image](https://github.com/BiAPoL/PoL-BioImage-Analysis-TS-GPU-Accelerated-Image-Analysis/assets/12660498/3522bdf3-ca6f-4647-ae54-c2eb2f179674)

**Comment by thawn** [comment]
downgrade jupyter in the container?

**Comment by haesleinhuepf** [comment]
`ipywidgets`?

**Comment by haesleinhuepf** [comment]
When starting the `Python 3` kernel (which I believe is the default installed) it seems to load the widgets... 

![image](https://github.com/BiAPoL/PoL-BioImage-Analysis-TS-GPU-Accelerated-Image-Analysis/assets/12660498/fd610f4a-58db-4ea4-bcf2-baf345f5862c)

Even if this doesn't work, I presume the [package] configuration of the kernel is key.

**Comment by thawn** [comment]
When I do the same in a conda environment on the cluster (without singularity), I get the same result:
![image](https://github.com/BiAPoL/PoL-BioImage-Analysis-TS-GPU-Accelerated-Image-Analysis/assets/1308449/033ac056-5612-452c-9732-9ea6eff60ccc)

**Comment by thawn** [comment]
using the default python3 kernel, stackview does not work for me (because I do not have it installed in the default environment), however the versions of ipywidgets and jupyterlab widgets are the same:
![image](https://github.com/BiAPoL/PoL-BioImage-Analysis-TS-GPU-Accelerated-Image-Analysis/assets/1308449/1d55b0f0-017d-4d25-a611-549f3ac2d127)

**Comment by haesleinhuepf** [comment]
Ok, I'll try to fix this on Thursday, or it will not be fixed (before the course).

**Comment by haesleinhuepf** [comment]
I'm closing this because we won't manage before the school
